CC := aarch64-unknown-linux-gnu-gcc
CFLAGS := $(CFLAGS) -static -O3 
LDFLAGS := -lm

BASEDIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
MACROS := $(BASEDIR)/pthread.m4
M4 := m4 
M4FLAGS := -Ulen -Uindex -P

AR := aarch64-unknown-linux-gnu-ar
RANLIB := aarch64-unknown-linux-gnu-ranlib

M4FLAGS += -D ATOMIC_BARRIERS
CFLAGS += -D ATOMIC_BARRIERS

ifndef BASEDIR
$(error Please define the BASEDIR variable)
endif

x = *
	
$(TARGET): $(OBJS) $(EXTRADEPS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS) $(LDFLAGS)

	
bindCores: M4FLAGS += -D BIND_CORES
bindCores: CFLAGS += -D BIND_CORES
bindCores: CFLAGS += -D_GNU_SOURCE
bindCores: TARGET := $(TARGET)-bindedCores
bindCores: $(TARGET)

bindThreads: M4FLAGS += -D BIND_THREADS
bindThreads: CFLAGS += -D BIND_THREADS
bindThreads: CFLAGS += -D_GNU_SOURCE
bindThreads: TARGET := $(TARGET)-bindedThreads
bindThreads: $(TARGET)
	
debug: $(OBJS) $(EXTRADEPS)
	$(CC) $(CFLAGS) -g -o $(TARGET) $(OBJS) $(LDFLAGS)
	
clean:
	rm -rf *.c *.h *.o $(TARGET)*

semiclean:
	rm -rf *.c *.h *.o
	
%.h: %.h.in
	$(M4) $(M4FLAGS) $(MACROS) $< > $@

%.c: %.c.in
	$(M4) $(M4FLAGS) $(MACROS) $< > $@

%.o: %.c $(EXTRADEPS)
	$(CC) -c $(CFLAGS) $<	

